services:
  frontend:
    build: ./frontend
    volumes:
      - .:/code
    networks:
      - nginx_proxy_manager_default

  backend:
    build: ./backend
    networks:
      - nginx_proxy_manager_default

networks:
  nginx_proxy_manager_default:
    external: true
