services:
  frontend:
    # will build ./frontend/Dockerfile
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - .:/code
  backend:
    # will build ./backend/Dockerfile
    build: ./backend
